name: delivery_os
description: Sistema de Gestão para Restaurantes e Delivery — Prisma V4.0
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Autenticação e Banco de Dados
  supabase_flutter: ^2.5.0

  # Navegação
  go_router: ^14.0.0

  # Gráficos animados (Dashboard de KPIs)
  fl_chart: ^0.68.0

  # Ícones estilo Lucide (equivalente ao lucide-react)
  lucide_flutter: ^1.14.0
  flutter_dotenv: ^6.0.1
  http: ^1.6.0
  provider: ^6.1.1
  shimmer: ^3.0.0
  dio: ^5.9.2
  pdf: ^3.12.0
  printing: ^5.14.3
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
